TheWorld/src/TheWorld/Models/Trip.cs
using System;
using System.Collections.Generic;

namespace TheWorld.Models
{
    public class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedOn { get; set; }
        public string Username { get; set; }
        public ICollection<Stop> Stops { get; set; }
    }
}

TheWorld/src/TheWorld/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
    public class ContactViewModel : ViewModelBase
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(4096, MinimumLength = 10)]
        public string Message { get; set; }
    }
}

TheWorld/src/TheWorld/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
    public class TripViewModel : ViewModelBase
    {
        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }

        public DateTime CreatedOn { get; set; } = DateTime.UtcNow;
    }
}

TheWorld/src/TheWorld/Controllers/Api/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.Extensions.Logging;
using TheWorld.Models;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Api
{
    [Authorize]
    public class TripsController : Controller
    {
        private readonly IWorldRepository _worldRepository;
        
        public TripsController(IWorldRepository worldRepository)
        {
            _worldRepository = worldRepository;
        }

        [HttpGet("api/trips")]
        public async Task<IActionResult> Get()
        {
            var trips = await _worldRepository.GetAllTripsAsync(User.Identity.Name);
            var tripViewModels = new List<TripViewModel>();
            
            foreach (var trip in trips)
            {
                var uri = Url.Link("GetTripById", new { id = trip.Id });
                var tripViewModel = Mapper.Map<TripViewModel>(trip);
                tripViewModel.Links.Self = uri;
                tripViewModels.Add(tripViewModel);
            }

            return Ok(tripViewModels);
        }

        [HttpPost("api/trips")]
        public async Task<IActionResult> Post([FromBody]TripViewModel tripViewModel)
        {
            if (tripViewModel == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var newTrip = Mapper.Map<Trip>(tripViewModel);
            newTrip.Username = User.Identity.Name;

            await _worldRepository.AddTripAsync(newTrip);
            var saved = await _worldRepository.SaveChangesAsync();

            if (!saved)
            {
                return new StatusCodeResult((int)HttpStatusCode.InternalServerError);
            }

            var newModel = Mapper.Map<TripViewModel>(newTrip);
            var uri = Url.Link("GetTripById", new {id = newTrip.Id});
            newModel.Links.Self = uri;
            return Created(uri, newModel);
        }

        [HttpGet("api/trips/{id}", Name = "GetTripById")]
        public async Task<IActionResult> Get(int id)
        {
            var trip = await _worldRepository.GetTripAsync(User.Identity.Name, id);

            if (trip == null)
            {
                return NotFound();
            }

            var model = Mapper.Map<TripViewModel>(trip);
            var uri = Url.Link("GetTripById", new { id = trip.Id });
            model.Links.Self = uri;
            return Ok(model);
        }

        [HttpDelete("api/trips/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            await _worldRepository.DeleteAsync(id);
            await _worldRepository.SaveChangesAsync();
            return NoContent();
        }
    }
}

TheWorld/src/TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TheWorld.Models;
using TheWorld.Services;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private readonly IEmailService _emailService;
        private readonly IConfigurationRoot _configurationRoot;
        private readonly IWorldRepository _worldRepository;
        private readonly ILogger<AppController> _logger;

        public AppController(
            IEmailService emailService, 
            IConfigurationRoot configurationRoot, 
            IWorldRepository worldRepository,
            ILogger<AppController> logger)
        {
            _emailService = emailService;
            _configurationRoot = configurationRoot;
            _worldRepository = worldRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Trips()
        {
            try
            {
                var trips = await _worldRepository.GetAllTripsAsync(User.Identity.Name);
                return View(trips);
            }
            catch (Exception exception)
            {
                _logger.LogError($"Error while retrieving trips.\n{exception}");
                return Redirect("/error");
            }
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com"))
            {
                ModelState.AddModelError("Email", "We don't support aol.com email addresses.");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            var toAddress = _configurationRoot["MailSettings:ToAddress"];
            _emailService.Send(toAddress, model.Email, "From The World", model.Message);
            ViewBag.UserMessage = "Message sent.";
            ModelState.Clear();
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

TheWorld/src/TheWorld/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}

<h2>About</h2>

TheWorld/src/TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Contact Page";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>Contact me</h2>
        <form method="post">
            <!--asp-validation-summary doesn't work-->
            <div asp-validation-summary="ModelOnly">
                @if (ViewBag.UserMessage != null)
            {
                    <div>@ViewBag.UserMessage</div>
                }
            </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" type="email" class="form-control"/>
                <span asp-validation-for="Email" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Message"></label>
                <textarea asp-for="Message" cols="40" rows="4" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>

            <div class="form-group">
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Cancel</a>
                <input type="submit" value="Send Message" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

TheWorld/src/TheWorld/Views/App/Index.cshtml
@model IEnumerable<TheWorld.Models.Trip>

@{
    ViewBag.Title = "Home Page (MVC)";
}

<div class="row">
    <div class="col-md-12">
        <h1>Welcome to The World!</h1>
        <p>This app will allow you to plan your trips.</p>
        <a asp-controller="App" asp-action="trips" class="btn btn-lg btn-success">View my trips</a>
    </div>
</div>

TheWorld/src/TheWorld/Views/App/Trips.cshtml
@model IEnumerable<TheWorld.Models.Trip>

@{
    ViewBag.Title = "Home Page (MVC)";
}

<div class="row">
    <div class="col-md-6">
        <h1>The World</h1>
        <p>This will be a fun website soon!</p>

        <form>
            <div class="form-group">
                <label>Date</label>
                <input class="form-control"/>
            </div>
            <div class="form-group">
                <label>Location</label>
                <input class="form-control"/>
            </div>
            <div>
                <input type="submit" value="Add" class="btn btn-success"/>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <h2>The map goes here.</h2>
        <ul>
            @foreach (var trip in Model)
            {
                <li>@trip.Name : @trip.CreatedOn.ToString("d")</li>
            }
        </ul>

    </div>
</div>