TheWorld/src/TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TheWorld.Models;
using TheWorld.Services;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private readonly IEmailService _emailService;
        private readonly IConfigurationRoot _configurationRoot;
        private readonly IWorldRepository _worldRepository;
        private readonly ILogger<AppController> _logger;

        public AppController(
            IEmailService emailService, 
            IConfigurationRoot configurationRoot, 
            IWorldRepository worldRepository,
            ILogger<AppController> logger)
        {
            _emailService = emailService;
            _configurationRoot = configurationRoot;
            _worldRepository = worldRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Trips()
        {
            try
            {
                var trips = await _worldRepository.GetAllTripsAsync(User.Identity.Name);
                return View(trips);
            }
            catch (Exception exception)
            {
                _logger.LogError($"Error while retrieving trips.\n{exception}");
                return Redirect("/error");
            }
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com"))
            {
                ModelState.AddModelError("Email", "We don't support aol.com email addresses.");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            var toAddress = _configurationRoot["MailSettings:ToAddress"];
            _emailService.Send(toAddress, model.Email, "From The World", model.Message);
            ViewBag.UserMessage = "Message sent.";
            ModelState.Clear();
            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

TheWorld/src/TheWorld/Controllers/Web/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TheWorld.Models.Identity;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Web
{
    public class AuthController : Controller
    {
        private readonly SignInManager<WorldIdentityUser> _signInManager;

        public AuthController(SignInManager<WorldIdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Trips", "App");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(
            LoginViewModel loginViewModel, 
            string redirectToUrl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var signInResult = await _signInManager.PasswordSignInAsync(
                loginViewModel.Username,
                loginViewModel.Password,
                true,
                false);

            if (signInResult.Succeeded)
            {
                return string.IsNullOrWhiteSpace(redirectToUrl) ? 
                    RedirectToAction("Trips", "App") : 
                    RedirectToAction(redirectToUrl);
            }

            ModelState.AddModelError("", "Username or password is incorrect.");
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await _signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "App");
        }
    }
}

TheWorld/src/TheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<div id="sidebar">
    @if (User.Identity.IsAuthenticated)
    {
        <img src="~/img/generic-person.png" alt="Your avatar" class="avatar"/>
        <span id="username">@User.Identity.Name</span>
    }
    <ul class="nav">
        <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
        <li><a asp-controller="App" asp-action="About">About</a></li>
        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>

        @if (User.Identity.IsAuthenticated)
        {
            <li><a asp-controller="App" asp-action="Trips">Trips</a></li>
            <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
        }
    </ul>
</div>
<div id="wrapper">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <button class="btn btn-primary btn-sm" id="toggle_menu">
                        <i class="fa fa-angle-left"></i>
                    </button>
                </li>
            </ul>
            <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#" class="btn btn-sm btn-info">
                        <i class="fa fa-save"></i> Save
                    </a>
                </li>
                <li>
                    <a href="#" class="btn btn-sm btn-info">
                        <i class="fa fa-print"></i> Print
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="main" class="container-fluid">
        @RenderBody()
    </div>
    <div id="footer" class="container-fluid">
        <div class="navbar navbar-inverse navbar-fixed-bottom">
            <h4 class="text-info text-center">&copy; 2016 Techniqly Travel</h4>
        </div>
    </div>
</div>
<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
    <script type="text/javascript" src="~/js/site.js"></script>
</body>
</html>